services:
  - type: web
    name: telegram-linkedin-bot
    env: python
    runtime: python
    repo: https://github.com/mechatemesgen/Linked-Bot
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://linked-bot.onrender.com/webhook
